services:
  claude-container:
    platform: linux/amd64
    build:
      context: .
      args:
        TZ: ${TZ:-America/Los_Angeles}                   # Pass host timezone
    #user: "${UID:-1000}:${GID:-1000}"                    # run as you
    user: "0:0"                                          # Run as root
    command: tail -f /dev/null                           # Keep container running
    environment:
      TZ: ${TZ:-UTC}                                     # Set container timezone
      ALLOWED_DOMAINS: >-
        registry.npmjs.org,
        api.anthropic.com,
        sentry.io,
        statsig.anthropic.com,
        statsig.com
    volumes:
      - ./:/workspace:rw                        # dedicated workspace folder, RW
      - ./.history:/commandhistory:rw                    # persist shell history
    ports:
      - 8183:8080
    tmpfs:
      - /tmp                                             # avoid writing to container FS
    read_only: false                                     # repo is already RW
    # cap_drop:
    #   - ALL
    # security_opt:
    #   - no-new-privileges
    pids_limit: 256
