import fs from "fs";
import path from "path";

/**
 * reapOrphanedSoffice — kill `soffice` processes left behind by an abrupt
 * death of the previous Node process, before `sweepAssemblyWork` deletes the
 * profile dirs they are actively using.
 *
 * Why this exists: `sofficeAssemble` spawns every `soffice` `detached: true`
 * (its own process group, so a hard-timeout kill can target the group rather
 * than orphaning `soffice.bin`). Detached also means the process SURVIVES its
 * parent. `custom:restart_passenger` fires on every Capistrano deploy, so a
 * deploy landing mid-merge restarts Node, hands a fresh and empty
 * `AssemblyJobRegistry` a free concurrency-1 slot, and leaves the old
 * `soffice` running. No in-process abort channel can reach across that
 * restart. On the deployed 2 vCPU / 2 GB swapless box, two headless
 * LibreOffice instances risk an OOM kill that may take Node rather than
 * `soffice`.
 *
 * Identity, not bare pids: a recorded pid is not trustworthy after a restart
 * (pid reuse), and recording one is unreliable anyway — `soffice` launches
 * via `oosplash`, which forks `soffice.bin`, so the pid we spawned may no
 * longer be the live process. Instead this SCANS `/proc` and kills only what
 * it can positively identify: a command line that is `soffice`'s AND carries
 * the per-job `-env:UserInstallation=…/<jobId>/…` argument for a job dir that
 * actually exists under `workRoot`. That argument is generated by us and
 * contains a UUID, which makes a false positive essentially impossible.
 *
 * Inert where identity cannot be established: if `/proc` cannot be read
 * (macOS dev, a container without `/proc`), this does nothing at all rather
 * than killing on a weaker signal — the same "unreadable → inert" precedent
 * `availableSystemMemory` sets for the low-memory guard.
 *
 * Safe ONLY under the single-process deployment constraint that
 * `sweepAssemblyWork` already documents: a second live worker's in-flight
 * merge would be killed by this.
 */

const PROC_ROOT = "/proc";

/**
 * Does this `/proc/<pid>/cmdline` belong to a LibreOffice process we spawned
 * for assembly job `jobId`?
 *
 * `cmdline` is NUL-separated (not space-separated) — callers pass the raw
 * file contents, so the fixtures in the tests carry real NULs too.
 *
 * Split from the scan so it is unit-testable on macOS, where `/proc` does not
 * exist and the whole reaper is otherwise inert — the same split
 * `parseMemAvailable` uses.
 */
export function matchesAssemblyJob(cmdline: string, jobId: string): boolean {
  if (jobId === "") {
    return false;
  }
  const args = cmdline.split("\0").filter((arg) => arg !== "");
  // The LibreOffice launcher chain is `soffice` -> `oosplash` -> `soffice.bin`
  // (see sofficeAssemble's process-group note), and `oosplash` execs with its
  // OWN argv[0] — so requiring the literal "soffice" would miss the very
  // middle process a restart is most likely to strand.
  if (!args.some((arg) => arg.includes("soffice") || arg.includes("oosplash"))) {
    return false;
  }
  // The per-job profile argument, not a bare substring match on the whole
  // command line: this is what makes the check false-positive-proof.
  return args.some((arg) => arg.startsWith("-env:UserInstallation=") && arg.includes(`/${jobId}/`));
}

/**
 * Parse the process-group id (field 5, `pgrp`) out of `/proc/<pid>/stat`.
 *
 * Field 2 (`comm`) is parenthesised and may itself contain spaces and
 * parentheses, so parsing starts after the LAST `)` — the standard way to
 * read this file. Returns `undefined` for anything unparseable.
 *
 * Reading `pgrp` rather than assuming the matched pid IS its group leader
 * matters: after `oosplash` forks, the process we can still identify is
 * usually the child, not the leader, and `process.kill(-pid)` on a non-leader
 * would just `ESRCH`.
 */
export function parseProcessGroupId(stat: string): number | undefined {
  const commEnd = stat.lastIndexOf(")");
  if (commEnd === -1) {
    return undefined;
  }
  const fields = stat
    .slice(commEnd + 1)
    .trim()
    .split(/\s+/);
  // fields[0] = state, [1] = ppid, [2] = pgrp
  const pgrp = Number(fields[2]);
  if (!Number.isInteger(pgrp) || pgrp <= 0) {
    return undefined;
  }
  return pgrp;
}

/**
 * Kill every identifiable orphaned `soffice` process group belonging to a job
 * dir under `workRoot`. Best-effort throughout: a failure here must never
 * stop server startup.
 */
export function reapOrphanedSoffice(workRoot: string): void {
  let jobIds: string[];
  try {
    jobIds = fs
      .readdirSync(workRoot, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name);
  } catch {
    return;
  }
  if (jobIds.length === 0) {
    return;
  }

  let pids: string[];
  try {
    pids = fs.readdirSync(PROC_ROOT).filter((name) => /^\d+$/.test(name));
  } catch {
    // No readable /proc: identity is unverifiable, so stay inert.
    return;
  }

  /** Deduped — the whole point is that several pids share one group. */
  const groupsToKill = new Map<number, string>();
  for (const pid of pids) {
    let cmdline: string;
    try {
      cmdline = fs.readFileSync(path.join(PROC_ROOT, pid, "cmdline"), "utf8");
    } catch {
      // The process exited mid-scan, or isn't ours to read.
      continue;
    }
    const jobId = jobIds.find((id) => matchesAssemblyJob(cmdline, id));
    if (jobId === undefined) {
      continue;
    }
    let pgrp: number | undefined;
    try {
      pgrp = parseProcessGroupId(fs.readFileSync(path.join(PROC_ROOT, pid, "stat"), "utf8"));
    } catch {
      continue;
    }
    if (pgrp !== undefined) {
      groupsToKill.set(pgrp, jobId);
    }
  }

  for (const [pgrp, jobId] of groupsToKill) {
    console.warn(
      `[reapOrphanedSoffice] killing orphaned soffice process group ${pgrp} left by assembly ` +
        `job ${jobId} (this process restarted mid-merge)`
    );
    try {
      process.kill(-pgrp, "SIGKILL");
    } catch (err) {
      console.warn("[reapOrphanedSoffice] process-group kill failed", err);
    }
  }
}
