name: Build Electron Executable
on:
  push:
    branches:
      - master

jobs:
  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: build-test
    - uses: actions/setup-node@master
      with:
        node-version: 12.22.6
    - name: Install dependencies
      run: yarn install
    - name: Build binary
      run: yarn build-desktop
      continue-on-error: true
    - name: Look at what we've got
      run: ls -l ./dist-desktop
    - name: Look at what we've got num2
      run: ls -l ./dist-desktop/mac
    - uses: actions/upload-artifact@v2
      with:
        name: platform-build
        path: |
          dist-desktop/Lessons*Luke*.dmg
          dist-desktop/Lessons*Luke*.exe
